/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    JourneyFormModal: typeof import('./components/JourneyFormModal.vue')['default']
    JourneyJournal: typeof import('./components/JourneyJournal.vue')['default']
    MoodPicker: typeof import('./components/MoodPicker.vue')['default']
    PhotoUploader: typeof import('./components/PhotoUploader.vue')['default']
    RichTextEditor: typeof import('./components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
